### ISSUE TITLE
How to switch off displaying of these two blue rectangles in white frames, which show progress of the dreamchess game?

### ISSUE THREAD

**Issue by sandra-a1b2c3** [dreamchess/dreamchess#16]
How to switch off displaying of these two blue rectangles in white frames, which show progress of the dreamchess game? ( above the board)?
And precisely, which lines and text need to change in binary file dreamchess or dreamer (in Debian dreamchess_0.2.0-3_i386.deb ) to switch off dispaying these rectangles?

Moreover people can't easy post comment here, (registration need, email , cell phones etc), so no strange that not many posts on host where you keep own project.

**Comment by renedes7dsc** [comment]
This is not direct response to your question but maybe will be helpful.
So to switch off displaying text "White" , "Black" above board in dreamchess game, you need:
1. Exctract dreamchess binary file from package dreamchess_0.2.0-3_i386.deb or copy installed dreamchess binary from /usr/games/dreamchess e.g.
sudo cp -R /usr/games/dreamchess /path/to/your/Desktop
2. Change file with vim
vim /path/to/your/Desktop/dreamchess
3. in opened vim search the pattern: Whit by typing in terminal:
/Whit
4.Find new pattern Whit by:
//
5. The same do with pattern: Blac
6. When you find values:
WhitfÇ@^De
BlacfÇ@^Dk
7. Press: esc a   , or esc i
vim should change into INSERT mode
8. Change:
WhitfÇ@^De
INTO:
fÇ@^D
(4 empty spaces)fÇ@^D(1empty space)

9. Change:
BlacfÇ@^Dk
INTO:
fÇ@^D
(4 empty spaces)fÇ@^D(1empty space)
10. Press: esc
11. Save changes in file by:
:wq
I don't know how author named these blue rectangles above the board in binary file, he could even named them by own dog name, so difficult to quess, so you need to ask Walter.
Besides it, to Walter if you want to survive your dreamchess project, you need to possible the people download .iso files with dreamchess games installed in linux OS distributions, because there is almost impossible for usual human compile working game in allien environment, where "group from authorities" remove whole packages, dependencies from repositories and force humans to use dependencies such as "netbios" or other tracking packages / dependencies. Additional there is no possible to download pure BIOS (whithout symilar "attractions"), what also require working linux OS (which disable these attractions). Maybe worth to renew BerliOS, or prepare dreamchess game installed in old linux distributions( Debian 4 , 5, 6 etc + Ubuntu) ready to download in .iso files.

**Comment by waltervn** [comment]
It is currently not possible to disable the rectangles without making changes to the source code and recompiling the game.
