### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by NathanBnm** [dreamchess/dreamchess#39]
I'd like to contribute but French isn't available on Weblate. Could you add it?

**Comment by waltervn** [comment]
Hi, It should be possible to add a new language, but in any case, I’ve added French now. Thanks! Walter Van: Nathan BonnemainsVerzonden: zondag 5 januari 2020 16:56Aan: dreamchess/dreamchessCC: SubscribedOnderwerp: [dreamchess/dreamchess] French translation (#39) I'd like to contribute but French isn't available on Weblate. Could you add it?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by NathanBnm** [comment]
>Hi, It should be possible to add a new language, but in any case.
>

Actually it's not possible for me to do this.

>I’ve added French now. Thanks! 
>

Thanks you

**Comment by waltervn** [comment]
Hi Nathan, That’s strange because other people have done it for other languages like Italian. But anyway, I hope it works for you now. Thanks for the help! Walter Van: Nathan BonnemainsVerzonden: zondag 5 januari 2020 17:21Aan: dreamchess/dreamchessCC: Walter van Niftrik; CommentOnderwerp: Re: [dreamchess/dreamchess] French translation (#39) Hi, It should be possible to add a new language, but in any case.Actually it's not possible for me to do this.I’ve added French now. Thanks!Thanks you—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by waltervn** [comment]
I saw your remark regarding the ellipsis. Unfortunately, DreamChess currently only supports ISO-8859-1 and that doesn’t contain the ellipsis. So ellipsis cannot be used in translations.

We hope to support unicode in the future, but right now we’re stuck with ISO-8859-1.

**Comment by NathanBnm** [comment]
Why can't you change?

**Comment by waltervn** [comment]
We can, and probably will at some point make the switch to unicode. However, it takes time and effort to adapt the code.

**Comment by NathanBnm** [comment]
What's the concerned code?

**Comment by waltervn** [comment]
It's mainly https://github.com/dreamchess/dreamchess/blob/master/dreamchess/src/gui/text.c that handles text rendering. It currently uses a pre-baked font texture containing only latin1 characters. It'd have to be replaced with a system that renders (and probably caches) unicode characters with a truetype library.

DreamChess is mostly legacy code, most of it was written 17 years ago.

**Comment by waltervn** [comment]
We're trying to get unicode working. If it works out I'll sort out the issue with the ellipses.

**Comment by comradekingu** [comment]
@NathanBnm https://hosted.weblate.org/projects/dreamchess/dreamchess/fr/ implemented :)

**Comment by NathanBnm** [comment]
> I saw your remark regarding the ellipsis. Unfortunately, DreamChess currently only supports ISO-8859-1 and that doesn’t contain the ellipsis. So ellipsis cannot be used in translations.
> 
> We hope to support unicode in the future, but right now we’re stuck with ISO-8859-1.

@waltervn there is still only two dots instead of three.
