### ISSUE TITLE
Saved games always designated as Normal difficulty

### ISSUE THREAD

**Issue by UndeadDevel** [dreamchess/dreamchess#53]
Using version 0.3.0-GIT on Fedora.

When starting a game on Easy or Normal difficulty, and saving it, the saved game is always displayed as being in Normal difficulty in the Load Game (or Save Game) windows. Whether the difficulty of Easy games actually changes to Normal or not I do not know.

Edit: actually, playing around with it further and assuming that both "Easy" and "Normal" are supposed to have 8 levels each, such that, e.g., "Easy level 5" would be significantly easier than "Normal level 1", the "Easy" difficulty seems to simply not work at all. At least it definitely seems to be easier to beat the "dreamer" engine on "Normal level 1" than on "Easy level 5". So maybe the issue is that it just always sets difficulty to "Normal" (which is fine, btw., since "Normal" is easy enough, but then the "Easy" option should be removed so as not to confuse the user).

**Comment by waltervn** [comment]
I cannot reproduce the saved game issue. It looks like Fedora is using revision 1c68b1e, which is part of a failed code rewrite from back in 2018. It was probably in the master branch when Fedora grabbed it, but it has since been abandoned. It also predates the last release, version 0.3.0.

Regarding the "Easy" vs "Normal" confusion. Originally we didn't have this option at all. Unfortunately, quite a few people still felt that dreamer was too difficult to beat even at level 1. To accommodate them, we added the "Easy" mode which has quiescence search disabled. At lower levels on "Easy" mode, dreamer should make some serious mistakes. As you go up to higher levels, the impact of disabling quiescence search will diminish, and at some point it will probably become a stronger opponent than "Normal" level 1.

**Comment by UndeadDevel** [comment]
Okay, thank you, also for the explanation of the difficulty feature!

I'll see if I can contact the Fedora repo maintainer for this or otherwise I may just install manually.
